- name: Install Docker and Docker Compose on Ubuntu
  block:
    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Check if Docker Compose is installed
      ansible.builtin.command: docker compose version
      register: docker_compose_installed
      ignore_errors: yes

    - name: Log Docker installation status
      ansible.builtin.debug:
        msg: "Docker is {{ 'installed' if docker_installed.rc == 0 else 'not installed' }}"

    - name: Log Docker Compose installation status
      ansible.builtin.debug:
        msg: "Docker Compose is {{ 'installed' if docker_compose_installed.rc == 0 else 'not installed' }}"

    - name: Get system architecture
      ansible.builtin.command: dpkg --print-architecture
      register: system_arch
      changed_when: false

    - name: Get Ubuntu version codename
      ansible.builtin.command: lsb_release -cs
      register: ubuntu_codename
      changed_when: false

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Add Docker GPG key
      ansible.builtin.shell:
        cmd: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Determine correct Ubuntu codename
      set_fact:
        ubuntu_codename_fixed: "{{ 'jammy' if ubuntu_codename.stdout == 'noble' else ubuntu_codename.stdout }}"

    - name: Add Docker repository (auto-detect architecture)
      ansible.builtin.shell:
        cmd: |
          echo "deb [arch={{ system_arch.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_codename_fixed }} stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Update apt package index again
      ansible.builtin.apt:
        update_cache: yes
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Install Docker and Docker Compose (if available in repo)
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
      ignore_errors: yes
      register: docker_install_status
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Enable and Start Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Change permissions for Docker socket
      ansible.builtin.command: sudo chmod 666 /var/run/docker.sock
      ignore_errors: yes
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0
  become: yes
